flag = -w -warn-error -unsafe -inline 10000000 ~/ocaml/must.ml

mycaml = ~/git_ocaml/ocamlopt -I ~/ocaml -nostdlib -I ~/git_ocaml/stdlib -I ~/git_ocaml/otherlibs/unix $(flag)
vanilla = ~/vanilla/ocamlopt  -I ~/ocaml -nostdlib -I ~/vcaml/lib/ocaml -I ~/vanilla/otherlibs/unix $(flag)
time = time -f "%e"
